version: '3'

services:

    mosquitto:
        container_name: mqtt-public
        image: eclipse-mosquitto
        ports:
        - 1883:1883
        - 8883:8883
        volumes:
        - ./mosquitto-data:/mosquitto/data
        - ./mosquitto-logs:/mosquitto/logs
        - ./mosquitto-conf:/mosquitto/config
        restart: unless-stopped